name: disable_battery_optimization_example
description: Demonstrates how to use the disable_battery_optimization plugin.
publish_to: "none"

environment:
  sdk: '>=3.3.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  disable_battery_optimization:
    path: ../

flutter:
  uses-material-design: true
