name: disable_battery_optimization
description: Flutter plugin to check and disable battery optimizations. Also shows custom steps to disable the optimizations in devices like mi, xiaomi, samsung, oppo, huawei, oneplus etc
version: 1.1.4
repository: https://github.com/thorito/disable_battery_optimization.git
issue_tracker: https://github.com/thorito/disable_battery_optimization/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: '>=3.3.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: in.jvapps.disable_battery_optimization
        pluginClass: DisableBatteryOptimizationPlugin

